name: go test
on:
  push:
    branches: 
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get modules
        run: go get
      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3800 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'wb_core' # The specified database which will be create
          mysql user: 'wanductbot' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'IF CHAT SEES THIS VI VON ZULUL' # Required if "mysql user" exists. The password for the "mysql user"
      - name: Run tests
        run: make test
