name: go test
on:
  # push:
  #   branches:
  # pull_request:
  #   branches:
  workflow_dispatch:

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get modules
        run: go get
      - name: Run tests
        run: make test
